### ISSUE TITLE
Compatibility with --enable=frozen-string-literal param

### ISSUE THREAD

**Issue by michal-granec** [rkh/hansi#2]
When I was handling a similar issue in the mustermann lib (https://github.com/sinatra/mustermann/pull/122) I found out that hansi is also modifying a frozen string literal. Right here: 

https://github.com/rkh/hansi/blob/master/lib/hansi/string_renderer.rb#L38

I will open an PR today.

**Comment by rkh** [comment]
I've published a new release with the fix.
